vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix: /uploads/products
            upload_destination: '%kernel.project_dir%/public/uploads/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        service_images:
            uri_prefix: /uploads/services
            upload_destination: '%kernel.project_dir%/public/uploads/services'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        blog_images:
            uri_prefix: /uploads/blog
            upload_destination: '%kernel.project_dir%/public/uploads/blog'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        before_after_avant:
            uri_prefix: /uploads/before_after
            upload_destination: '%kernel.project_dir%/public/uploads/before_after'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        before_after_apres:
            uri_prefix: /uploads/before_after
            upload_destination: '%kernel.project_dir%/public/uploads/before_after'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer