<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260612195105 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE order_status_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, statut VARCHAR(30) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, commentaire TEXT DEFAULT NULL, commande_id INT NOT NULL, changed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_471AD77E82EA2E54 ON order_status_history (commande_id)');
        $this->addSql('CREATE INDEX IDX_471AD77E828AD0A0 ON order_status_history (changed_by_id)');
        $this->addSql('ALTER TABLE order_status_history ADD CONSTRAINT FK_471AD77E82EA2E54 FOREIGN KEY (commande_id) REFERENCES "order" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_status_history ADD CONSTRAINT FK_471AD77E828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE order_status_history DROP CONSTRAINT FK_471AD77E82EA2E54');
        $this->addSql('ALTER TABLE order_status_history DROP CONSTRAINT FK_471AD77E828AD0A0');
        $this->addSql('DROP TABLE order_status_history');
    }
}
