<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260821123500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_coffret_items DROP CONSTRAINT fk_dc632213126f525e');
        $this->addSql('ALTER TABLE product_coffret_items DROP CONSTRAINT fk_dc632213ce07368d');
        $this->addSql('ALTER TABLE product_related_products DROP CONSTRAINT fk_9bb5700b24136e58');
        $this->addSql('ALTER TABLE product_related_products DROP CONSTRAINT fk_9bb5700b3df63ed7');
        $this->addSql('DROP TABLE product_coffret_items');
        $this->addSql('DROP TABLE product_related_products');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE product_coffret_items (coffret_id INT NOT NULL, item_id INT NOT NULL, PRIMARY KEY (coffret_id, item_id))');
        $this->addSql('CREATE INDEX idx_dc632213126f525e ON product_coffret_items (item_id)');
        $this->addSql('CREATE INDEX idx_dc632213ce07368d ON product_coffret_items (coffret_id)');
        $this->addSql('CREATE TABLE product_related_products (product_source INT NOT NULL, product_target INT NOT NULL, PRIMARY KEY (product_source, product_target))');
        $this->addSql('CREATE INDEX idx_9bb5700b24136e58 ON product_related_products (product_target)');
        $this->addSql('CREATE INDEX idx_9bb5700b3df63ed7 ON product_related_products (product_source)');
        $this->addSql('ALTER TABLE product_coffret_items ADD CONSTRAINT fk_dc632213126f525e FOREIGN KEY (item_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_coffret_items ADD CONSTRAINT fk_dc632213ce07368d FOREIGN KEY (coffret_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_related_products ADD CONSTRAINT fk_9bb5700b24136e58 FOREIGN KEY (product_target) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_related_products ADD CONSTRAINT fk_9bb5700b3df63ed7 FOREIGN KEY (product_source) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395');
        $this->addSql('DROP TABLE reset_password_request');
    }
}
