<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260612140313 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, slug VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, conseils_utilisation TEXT DEFAULT NULL, prix NUMERIC(10, 2) NOT NULL, prix_promo NUMERIC(10, 2) DEFAULT NULL, date_debut_promo TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_fin_promo TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, stock_quantity INT DEFAULT NULL, is_rupture BOOLEAN NOT NULL, is_nouveaute BOOLEAN NOT NULL, is_coffret BOOLEAN NOT NULL, is_mise_en_avant BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D34A04AD12469DE2 ON product (category_id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD12469DE2');
        $this->addSql('DROP TABLE product');
    }
}
