<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260805114247 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE coffret (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, prix NUMERIC(10, 2) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE coffret_products (coffret_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (coffret_id, product_id))');
        $this->addSql('CREATE INDEX IDX_5DAE3E25CE07368D ON coffret_products (coffret_id)');
        $this->addSql('CREATE INDEX IDX_5DAE3E254584665A ON coffret_products (product_id)');
        $this->addSql('ALTER TABLE coffret_products ADD CONSTRAINT FK_5DAE3E25CE07368D FOREIGN KEY (coffret_id) REFERENCES coffret (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE coffret_products ADD CONSTRAINT FK_5DAE3E254584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product ALTER is_promo DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE coffret_products DROP CONSTRAINT FK_5DAE3E25CE07368D');
        $this->addSql('ALTER TABLE coffret_products DROP CONSTRAINT FK_5DAE3E254584665A');
        $this->addSql('DROP TABLE coffret');
        $this->addSql('DROP TABLE coffret_products');
        $this->addSql('ALTER TABLE product ALTER is_promo SET DEFAULT false');
    }
}
