<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260612201238 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(150) NOT NULL, slug VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, contenu TEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, meta_description VARCHAR(255) DEFAULT NULL, prix NUMERIC(10, 2) DEFAULT NULL, duree INT DEFAULT NULL, categorie VARCHAR(30) NOT NULL, is_published BOOLEAN NOT NULL, position INT NOT NULL, lien_fresha VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE service');
    }
}
