<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260612193408 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "order" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_commande VARCHAR(50) NOT NULL, montant_total NUMERIC(10, 2) NOT NULL, stripe_payment_intent_id VARCHAR(255) DEFAULT NULL, statut VARCHAR(30) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, livraison_nom VARCHAR(100) NOT NULL, livraison_rue VARCHAR(255) NOT NULL, livraison_complement VARCHAR(255) DEFAULT NULL, livraison_code_postal VARCHAR(10) NOT NULL, livraison_ville VARCHAR(100) NOT NULL, livraison_pays VARCHAR(100) NOT NULL, livraison_telephone VARCHAR(20) NOT NULL, livraison_email VARCHAR(180) NOT NULL, delivery_method VARCHAR(30) NOT NULL, shipping_cost NUMERIC(10, 2) NOT NULL, client_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F529939819EB6921 ON "order" (client_id)');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F529939819EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F529939819EB6921');
        $this->addSql('DROP TABLE "order"');
    }
}
