# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
parameters:
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe_webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Controller\Front\CheckoutController:
        arguments:
            $stripePublicKey: '%stripe_public_key%'
            $stripeSecretKey: '%stripe_secret_key%'
        tags: ['controller.service_arguments']

    App\Controller\StripeWebhookController:
        arguments:
            $stripeSecretKey: '%stripe_secret_key%'
            $stripeWebhookSecret: '%stripe_webhook_secret%'
        tags: ['controller.service_arguments']

    App\Service\MailerService:
        arguments:
            $mailerFrom: '%env(MAILER_FROM)%'
            $mailerAdmin1: '%env(MAILER_ADMIN_1)%'
            $mailerAdmin2: '%env(MAILER_ADMIN_2)%'

    App\Command\ImportProductImagesCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'